### ISSUE TITLE
Update to normalize 8

### ISSUE THREAD

**Issue by vladshcherbin** [csstools/postcss-normalize#26]
Normalize 8 is out, it would be great to have this project updated to the latest version 🙏

**Comment by jonathantneal** [comment]
Sorry, and please don’t take my frustration as directed at you, but it wouldn’t be great, because Normalize 8 has a really bad bug, and the maintainer doesn’t make the time for that project that it needs. Also, let’s look at the feature list:

- Remove support for older browsers Android 4, lte IE 9, lte Safari 7.
^ Unnecessary (and unhelpful) for this project

- Don't remove search input cancel button in Chrome/Safari
^ This is one feature

- Form inputs inherit font-family.
^ This is an opinionated change, not a normalization, and this project doesn’t include the opinionated parts of normalize

- Fix text decoration in Safari 8+.
^ This is the other feature

However, the support removal was too eager, and `<main>` for IE10 and IE11 was lost.

So, I will add the features separately in my fork this week. They are:

- Remove `[type="search"]::-webkit-search-cancel-button` selector
- Remove `-webkit-text-decoration-skip: objects;` declaration

**Comment by vladshcherbin** [comment]
@jonathantneal thanks for great explanation.

I was carrying a minimal reset/normalize file from project to project and thought I could replace it with normalize with browserslist support. After reading about all this surprises I guess I'll just review my file and continue using it 🤦‍♂️ 

Feel free to close this issue anytime :)

**Comment by jonathantneal** [comment]
I understand. The goal of `postcss-normalize` is about _just_ fixing browser inconsistencies between browsers _you_ support (via browserslist).

**Comment by sntran** [comment]
Hi @jonathantneal ,

I see that `[type="search"]::-webkit-search-cancel-button` and `-webkit-text-decoration-skip: objects;` are still in the bundled `normalize.css`. Was there any complication in removing them?
