### ISSUE TITLE
@import-normalize "opinionated.css"; doesn't actually work

### ISSUE THREAD

**Issue by marcofugaro** [csstools/postcss-normalize#46]
Hey, I've tried in my css

```postcss
@import-normalize "opinionated.css";
```

However, it is not recognized, and the output remains

```postcss
@import-normalize "opinionated.css";
```

This should be supported since it's in the README and also a test is needed for this feature.

**Comment by ghost** [comment]
It doesn't seem to be working with [Create React App (3.4.1)](https://github.com/csstools/postcss-normalize/blob/master/INSTALL.md#create-react-app) either:

![image](https://user-images.githubusercontent.com/25172271/82121576-87daab00-9764-11ea-8f58-d957c503dcf5.png)

**Comment by Dan503** [comment]
This one issue basically makes this otherwise really cool tool completely impossible to use in most modern day projects :(

**Comment by marcofugaro** [comment]
@Dan503 in the meantime, you can import it like this:

```css
@import 'normalize/opinionated';
```

and have the [import plugin](https://github.com/postcss/postcss-import) ignore that line: 

```js
postcssImport({
  filter(importPath) {
    return !importPath.includes('normalize')
  },
}),
```

**Comment by Dan503** [comment]
My problem is that Sass tries to import a file that doesn't exist.

And i tried using a basic css file instead of an scss file but I'm using a Gatsby project and I think Gatsby tries to bundle all the CSS up into one thing so when i tried to add the import statement it complained about not being able to find the file.

**Comment by marcofugaro** [comment]
@Dan503 you have to tell Sass to ignore that import, don't know if there is a way though.

**Comment by Dan503** [comment]
I was able to get around Sass by importing a plain `.css` file. Sass doesn't try to do anything with plain css files.

I still had a problem though because Gatsby still tried to import the css before compiling.

It doesn't add that much bloat so I'm just importing the whole file and not using postcss-normalize.

**Comment by jonathantneal** [comment]
I’m interested in knowing the cause of this.

The entire point of this library is so that exactly your kind of usage should work.

**Comment by adamwathan** [comment]
Here's a minimum reproduction:

https://github.com/adamwathan/postcss-normalize-bug

`@import-normalize "opinionated.css";` is just ignored. Going to see if I can fix as I'd like to move Tailwind to this but we need to be able to do it without having to explain to people the tweaks they need to make to any of their postcss-import configuration or we're going to get a lot of issues.

**Comment by adamwathan** [comment]
Okay so after a bit of source-diving, you can make this work currently using the following syntax:

```
@import-normalize "normalize/opinionated.css";
```

Perhaps we just need to update the README here and not any actual code?

**Comment by romainmenke** [comment]
README updated and added test coverage for `@import-normalize "normalize/opinionated.css";`.

Thank you everyone
